name: hpc-python-course
channels:
  - conda-forge
  - nvidia
  - numba
  - defaults

dependencies:
  # Python and core scientific stack
  - python=3.9
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - pandas>=1.3.0
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - notebook>=6.4.0
  
  # Parallel computing libraries
  - joblib>=1.1.0
  - dask>=2021.10.0
  - numba>=0.56.0
  
  # System monitoring and profiling
  - psutil>=5.8.0
  - memory_profiler>=0.60.0
  - line_profiler>=3.3.0
  
  # GPU computing (optional - will be skipped if no GPU)
  - cupy>=9.0.0
  - cudatoolkit>=11.2
  
  # Development and testing tools
  - pytest>=6.2.0
  - black>=21.0.0
  - isort>=5.9.0
  - flake8>=3.9.0
  
  # Additional scientific libraries
  - scikit-learn>=1.0.0
  - seaborn>=0.11.0
  - tqdm>=4.62.0
  
  # Documentation and presentation
  - sphinx>=4.0.0
  - myst-parser>=0.15.0
  
  # Optional: additional performance libraries
  - pip
  - pip:
    - pympler>=0.9  # Memory profiling
    - py-spy>=0.3.0  # Python profiler
    - scalene>=1.5.0  # High-performance Python profiler
    
# Environment variables for optimal performance
variables:
  # NumPy threading
  OMP_NUM_THREADS: 4
  MKL_NUM_THREADS: 4
  OPENBLAS_NUM_THREADS: 4
  
  # CUDA settings (if GPU available)
  CUDA_VISIBLE_DEVICES: 0
  
  # Python optimizations
  PYTHONUNBUFFERED: 1